language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  allow_failures:
    - python: '3.6'
    - python: 'nightly'
env:
  - DEP="Flask==0.11"
  - DEP="Flask==0.12"
  - DEP="Flask==1.0"
  - DEP="Flask==1.0.2"
  - DEP="Flask"
install: 
  - pip install ${DEP}
  - pip install flake8
script: 
  - python -m unittest discover
  - flake8 --exclude=examples --max-line-length=100
notifications:
  email: false

