language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - FLASK=0.12
  - FLASK=1.0
  - FLASK=latest
matrix:
  allow_failures:
    - env: FLASK=latest
install: 
  - pip install Flask==${FLASK}
script: 
  - python -m unittest discover

